[project]
name = "zillow-visualization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.1.3",
    "pandas>=2.2.3",
    "polars>=1.17.1",
    "psycopg2-binary>=2.9.9",
    "sqlalchemy>=2.0.35",
]
